### ISSUE TITLE
where is mxnet_reader?

### ISSUE THREAD

**Issue by wang-kangkang** [GuoQuanhao/arcface-Paddle#1]
from mxnet_reader import recordio
ModuleNotFoundError: No module named 'mxnet_reader'

mxnet_reader文件到哪里下载？

**Comment by wang-kangkang** [comment]
找到了，mxnet_reader就在“模型和数据集读取代码下载”里，看起来这个链接不只是用作测试文件

**Comment by GuoQuanhao** [comment]
是的，里面包含了所有的资源文件，你可以在这里找到最新的arcface，https://github.com/deepinsight/insightface/tree/master/recognition/arcface_paddle
